import type { Product } from "@/types";

export const dummyProducts: Product[] = [
  {
    id: "box-logo-tee",
    name: "Box Logo Tee",
    description: "Oversized graphic tee with puff-print back hit.",
    price: 45,
    compareAt: null,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDa6TYsnhzBruBIElH1Gi7TcGAUZ3qFcTDnynhrYfCDwwjufjc59Zlnr_RWyOwO9m7FqF-0Og0dOLFBVKpWX3f9lWM39xCAlECXuXPvbudrZUtwWyK6H-mGOsrG76JOf3nkSjSpeAKDBT8bzxCHcx3ATlA23t01uD46vlJ-wl60lVU0vEWLkmU7LJ2YWgHJzw8snqHuwep0iF16YTjGECJXJ0Xye6Bt8ZkqznJhPZyrhkGqnrkNeUTl7H3TCz6e12aHgpDXLmlK_Jmy",
    ],
    category: "accessories",
    badge: "New",
    ratingAvg: 4.6,
    reviewsCount: 128,
    stock: 25,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tech-cargo-v2",
    name: "Tech Cargo V2",
    description: "Water-resistant cargo pants with modular pockets.",
    price: 120,
    compareAt: 140,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAji2QR66FfCtYWmVejzlN2E9r9-6D-LbXSaxTgHLJr9RyVhkn55swnmSH5eobIiz4_dXxD6us71jewpaeXpOhCI-FtT8JnrPgORJIvlrj8nhSlsnS4V7ouGjge4fofTnXw7KSunj8V8nXX228eF0uFGn4tixNJvm1MeobSzsRIUzIljSKWALYTwYRIyYMH9pNuqZLTY5EKw_NxBYpraYu46tyVsvW7D7EctPFWJj0XeK-TpoD09vCkTH-INtmP8JvLrTvHTlbAVNNX",
    ],
    category: "bottoms",
    badge: "Hot",
    ratingAvg: 4.8,
    reviewsCount: 89,
    stock: 18,
    createdAt: new Date().toISOString(),
  },
  {
    id: "distressed-denim",
    name: "Distressed Denim",
    description: "Vintage-wash denim jacket with hand-finishing.",
    price: 185,
    compareAt: null,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBXFN-YcAsmeg9fdBatL89dPwdUn0pmmV2vppj-LxKm95R4myHSCML89H8B23MGHxdQNcDCdhanWTN_b9NiLlptFDh00Coti5qwqWEhxdPweh8_tM6e8Y55UtvyErK-YAe2IOu190rStn_IuXlFd78j54Vu4GY-md04nrtUU1ypFMGwoYsNSGS5JZ4LOM0kB13Dcu1H78mfDboZGAoPz5BPNhVKIMQbtk0DggpMTaWcaNz7JRm-fPF-nT3v5DlmbFtA5rPSS3I_Cf9F",
    ],
    category: "outerwear",
    badge: "Limited",
    ratingAvg: 4.9,
    reviewsCount: 56,
    stock: 12,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tactical-bucket",
    name: "Tactical Bucket",
    description: "Reversible bucket hat with hidden stash pocket.",
    price: 35,
    compareAt: null,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCWMyIj-7Z7YXkFkWMD7kLGW9JNKPRnvNGv3YXylaIfhdoOqfzt6jpVUJ_DYFemL6WZ11Nv0IxL2Moeq8vnXzOppmZza0HgZxa91OjnWp_YcSU1ayJt_5uLonLuAfPCvKWuH8X6mqY54ADYu1my_LvIfaiPdTjS5rd4alPNX27Y-wP3SlbnG1r_GFm4piuGm7pxuB5EBYZwvQDmfPFTTCw0GRfMQjOnOgk8fyrMqgcGfj2Mkqxo_vL9jBfvw6Tb3CQNLbCjyIrIE2aX",
    ],
    category: "headwear",
    badge: "Trending",
    ratingAvg: 4.4,
    reviewsCount: 72,
    stock: 40,
    createdAt: new Date().toISOString(),
  },
  {
    id: "oversized-hoodie",
    name: "Oversized Hoodie",
    description: "Ultra-soft fleece hoodie with drop shoulders.",
    price: 65,
    compareAt: 85,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCKpq_Hh-kygxufcOV2ABtEE4Dtntc112znR_6Cp3oWYTXSKqK8rQH2kp5T2JiUCeqRa7BLRyB_ygeAZGk2xDMkZqyhHAavkx2mYfQ54n2morNkcooB4-U1iicfzaAB_Av32PMtQw00h8jTyF1J2L2g8Lriglr1YddvyUIU0XyCLCBl7GsHzdjn4ZN143YsELJuOs5BLzDTRItAtaFNQxy1xo-01d52VJYT2JfYtRtRTq_ePvgbWpM3v62QHdz6b0OyEH8LlcVJSDRa",
    ],
    category: "essentials",
    badge: "Best Seller",
    ratingAvg: 4.7,
    reviewsCount: 310,
    stock: 30,
    createdAt: new Date().toISOString(),
  },
  {
    id: "utility-vest",
    name: "Utility Vest",
    description: "Tactical utility vest with adjustable straps.",
    price: 95,
    compareAt: null,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBsKrx7EIUMDpZ872Ou5dkKTQQpcC5Rn71fkDa3tlCyqVaYNI_jPhAPFJJU2Iy-BqLJgQFWykVTslslic14oqUksnRzyeJjYhtpM2nd9l5WOgfP_mz24Hv2lk28sie2HeISF67wZheEBdRU0NFeICUnKZNktleCw7Gy79iuUa2LGkVpRhgr5V0_AQmK39KALQVdXvmqD_zyVDe8wWltLF264B4h43FKEx7Ie_jsaXeFP8gQ-ENZa83_i06VG29DflFqccsaIbnJOdsP",
    ],
    category: "outerwear",
    badge: "Hot",
    ratingAvg: 4.3,
    reviewsCount: 64,
    stock: 20,
    createdAt: new Date().toISOString(),
  },
  {
    id: "covert-parka",
    name: "Covert Parka",
    description: "Storm-ready parka with removable liner.",
    price: 240,
    compareAt: 280,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDnHAs9vITbWm-VxtoQdYVD38TWUC-OvwvYRDLmb0cO_TdAyj7bZ9LyNpz5ltPMsi2aOh9rBaeiHHRVSwTc5zt-4FrzPyEGb13uQ62we_brc1ruR3DmpMITdw_SJjeBfmxzLEuTRmyuJUqz0SUVUvbP2UROlJ5UQ1JjKxk_lGvhNHHnEjOwi-7iJUu7SAbQFWoL8VFAy6ctHst5ujxhcu4FFamkLldo3OP_iocoLJ1xiV_iRV9RFMMs4PK7osc0DU5Bs2bq4BoGyyao",
    ],
    category: "outerwear",
    badge: "Limited",
    ratingAvg: 4.9,
    reviewsCount: 41,
    stock: 8,
    createdAt: new Date().toISOString(),
  },
  {
    id: "shadow-track-pants",
    name: "Shadow Track Pants",
    description: "Slim track pants with reflective taping.",
    price: 98,
    compareAt: null,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCFdjqwkVoyEJpSVs8rfa2Egxr8TPkPO8iU7Ls4PcNpfeLys2oDKqKZvBoEVYDb01wQMq-Crf-H4Z-J8OL0ndV283JlrTL2eqLDifEJOqtCT9MlGLWY-v7U8N-lZRprRFuDFWZ0Dm4yr0wOLqE3obpILAX2A0HYZn-Tr9pgSZdEkWqvGYRCmQg4M6T3-d7mvlGAFZvwo-I6GNeXxZmHR-nQaJvTXhnWDywq729vsTbvTbW5JyO_Y7KfTKUvl00W41-_EaW9Kh5uKRaf",
    ],
    category: "pants",
    badge: "Trending",
    ratingAvg: 4.5,
    reviewsCount: 97,
    stock: 22,
    createdAt: new Date().toISOString(),
  },
  {
    id: "atelier-blazer",
    name: "Atelier Wool Blazer",
    description: "Single-breasted Italian wool blazer with hand-finished lapels and satin lining.",
    price: 420,
    compareAt: 520,
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "jackets",
    badge: "Limited",
    ratingAvg: 4.9,
    reviewsCount: 142,
    stock: 6,
    createdAt: new Date().toISOString(),
  },
];
