import { dummyProducts } from "@/lib/dummyData";
import type { Product } from "@/types";

export const luxuryProducts: Product[] = [
  {
    id: "atelier-tee",
    slug: "atelier-tee",
    name: "Atelier Cotton Tee",
    description: "Heavyweight cotton tee with bound collar and matte finish.",
    shortDescription: "Heavyweight cotton tee with bound collar and matte finish.",
    price: 120,
    compareAt: null,
    currency: "USD",
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80"],
    category: "tees",
    badge: "New",
    ratingAvg: 4.8,
    reviewsCount: 54,
    stock: 20,
    inStock: true,
    createdAt: new Date().toISOString(),
    isNew: true,
    brand: "Fit In Studio",
    sizes: ["XS", "S", "M", "L", "XL"],
    highlights: ["Heavyweight cotton", "Bound collar", "Matte finish"],
    features: ["Heavyweight cotton", "Bound collar", "Matte finish"],
    sku: "FIT-TEE-001",
  },
  {
    id: "sculpted-tee",
    slug: "sculpted-tee",
    name: "Sculpted Jersey Tee",
    description: "Mercerized jersey tee with structured drape and smooth handfeel.",
    shortDescription: "Mercerized jersey tee with structured drape and smooth handfeel.",
    price: 135,
    compareAt: 160,
    currency: "USD",
    images: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80"],
    category: "tees",
    badge: "Hot",
    ratingAvg: 4.7,
    reviewsCount: 72,
    stock: 18,
    inStock: true,
    createdAt: new Date().toISOString(),
    isNew: true,
    brand: "Atelier Line",
    sizes: ["S", "M", "L", "XL"],
    highlights: ["Mercerized jersey", "Structured drape", "Smooth handfeel"],
    features: ["Mercerized jersey", "Structured drape", "Smooth handfeel"],
    sku: "FIT-TEE-002",
  },
  {
    id: "drape-top",
    slug: "drape-top",
    name: "Draped Silk Top",
    description: "Fluid silk top cut on the bias with minimal seams.",
    shortDescription: "Fluid silk top cut on the bias with minimal seams.",
    price: 290,
    compareAt: null,
    currency: "USD",
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80"],
    category: "tops",
    badge: "Limited",
    ratingAvg: 4.9,
    reviewsCount: 41,
    stock: 12,
    inStock: true,
    createdAt: new Date().toISOString(),
    isNew: true,
    brand: "Fit In Atelier",
    sizes: ["XS", "S", "M", "L"],
    highlights: ["Bias cut", "Minimal seams", "Fluid silk"],
    features: ["Bias cut", "Minimal seams", "Fluid silk"],
    sku: "FIT-TOP-003",
  },
  {
    id: "linen-shirt",
    slug: "linen-shirt",
    name: "Pure Linen Shirt",
    description: "Italian linen shirt with concealed placket and crisp collar.",
    shortDescription: "Italian linen shirt with concealed placket and crisp collar.",
    price: 260,
    compareAt: null,
    currency: "USD",
    images: ["https://images.unsplash.com/photo-1521572267363-8c9c9e1e3a59?auto=format&fit=crop&w=1200&q=80"],
    category: "tops",
    badge: "Trending",
    ratingAvg: 4.6,
    reviewsCount: 33,
    stock: 15,
    inStock: true,
    createdAt: new Date().toISOString(),
    isNew: true,
    brand: "Edition",
    sizes: ["S", "M", "L"],
    highlights: ["Italian linen", "Concealed placket", "Crisp collar"],
    features: ["Italian linen", "Concealed placket", "Crisp collar"],
    sku: "FIT-TOP-004",
  },
  {
    id: "sculpted-hoodie",
    slug: "sculpted-hoodie",
    name: "Sculpted Fleece Hoodie",
    description: "Structured fleece with dropped shoulders and clean hem.",
    shortDescription: "Structured fleece with dropped shoulders and clean hem.",
    price: 210,
    compareAt: 240,
    currency: "USD",
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80"],
    category: "hoodies",
    badge: "Best Seller",
    ratingAvg: 4.8,
    reviewsCount: 120,
    stock: 25,
    inStock: true,
    createdAt: new Date().toISOString(),
    isNew: true,
    brand: "Core Line",
    sizes: ["XS", "S", "M", "L", "XL"],
    highlights: ["Structured fleece", "Dropped shoulders", "Clean hem"],
    features: ["Structured fleece", "Dropped shoulders", "Clean hem"],
    sku: "FIT-HOOD-005",
  },
  {
    id: "modal-tee",
    slug: "modal-tee",
    name: "Modal Signature Tee",
    description: "Featherweight modal tee with smooth drape and minimal seams.",
    shortDescription: "Featherweight modal tee with smooth drape and minimal seams.",
    price: 115,
    compareAt: null,
    currency: "USD",
    images: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80"],
    category: "tees",
    badge: "New",
    ratingAvg: 4.5,
    reviewsCount: 25,
    stock: 30,
    inStock: true,
    createdAt: new Date().toISOString(),
    isNew: true,
    brand: "Fit In Studio",
    sizes: ["XS", "S", "M", "L"],
    highlights: ["Featherweight modal", "Smooth drape", "Minimal seams"],
    features: ["Featherweight modal", "Smooth drape", "Minimal seams"],
    sku: "FIT-TEE-006",
  },
];

export const allProducts: Product[] = [...luxuryProducts, ...dummyProducts.map((p) => ({ ...p, slug: p.slug ?? p.id }))];

export function getProductSlugs() {
  return allProducts.map((p) => p.slug ?? p.id);
}

export function getProductBySlug(slug: string) {
  const normalized = decodeURIComponent(slug).toLowerCase();
  return allProducts.find((p) => (p.slug ?? p.id).toLowerCase() === normalized);
}
